# Generated by Django 4.0.1 on 2022-01-21 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_userprofile_agent_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
    ]
